services:
  mysql:
    image: 'mysql:8.0'
    ports:
      # IZQUIERDA: Puerto de tu PC (usamos 3307 para evitar conflicto)
      # DERECHA: Puerto interno del contenedor (siempre 3306)
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'alumno'
      MYSQL_PASSWORD: 'alumno'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - sail

  # Opcional: Interfaz visual para ver la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - '8081:80' # Acceder√°s por localhost:8081
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  mysql-data:
    driver: local
